export const employees = [
  {
    id: 1,
    employeeName: "Amit Sharma",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        id: 101,
        taskTitle: "Prepare Sales Report",
        taskDescription: "Compile and prepare the monthly sales report",
        taskPriority: "High",
        category: "Reporting",
        creationDate: "2026-01-05",
        dueDate: "2026-01-10",
        status: "active",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 102,
        taskTitle: "Client Follow-up",
        taskDescription: "Follow up with pending client emails",
        taskPriority: "Low",
        category: "Communication",
        creationDate: "2026-01-07",
        dueDate: "2026-01-12",
        status: "new",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 103,
        taskTitle: "Data Cleanup",
        taskDescription: "Clean outdated entries from CRM",
        taskPriority: "Low",
        category: "Maintenance",
        creationDate: "2026-01-03",
        dueDate: "2026-01-06",
        status: "completed",
        removalRequested: false,
        removalRequestedAt: null,
      },
    ],
  },

  {
    id: 2,
    employeeName: "Neha Verma",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        id: 201,
        taskTitle: "Bug Fixing",
        taskDescription: "Fix UI bugs on dashboard",
        taskPriority: "High",
        category: "Development",
        creationDate: "2026-01-06",
        dueDate: "2026-01-09",
        status: "new",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 202,
        taskTitle: "Code Review",
        taskDescription: "Review PRs from teammates",
        taskPriority: "Low",
        category: "Development",
        creationDate: "2026-01-04",
        dueDate: "2026-01-07",
        status: "completed",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 203,
        taskTitle: "Optimize Queries",
        taskDescription: "Improve database query performance",
        taskPriority: "High",
        category: "Performance",
        creationDate: "2026-01-02",
        dueDate: "2026-01-05",
        status: "failed",
        removalRequested: false,
        removalRequestedAt: null,
      },
    ],
  },

  {
    id: 3,
    employeeName: "Rohit Mehta",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        id: 301,
        taskTitle: "Design Landing Page",
        taskDescription: "Create UI design for new landing page",
        taskPriority: "High",
        category: "Design",
        creationDate: "2026-01-08",
        dueDate: "2026-01-14",
        status: "new",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 302,
        taskTitle: "Update Brand Assets",
        taskDescription: "Refresh logo and color palette",
        taskPriority: "Low",
        category: "Design",
        creationDate: "2026-01-01",
        dueDate: "2026-01-04",
        status: "completed",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 303,
        taskTitle: "Prototype Review",
        taskDescription: "Review Figma prototype with team",
        taskPriority: "Low",
        category: "Review",
        creationDate: "2026-01-05",
        dueDate: "2026-01-08",
        status: "failed",
        removalRequested: false,
        removalRequestedAt: null,
      },
    ],
  },

  {
    id: 4,
    employeeName: "Pooja Singh",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        id: 401,
        taskTitle: "Write Test Cases",
        taskDescription: "Create unit test cases for auth module",
        taskPriority: "High",
        category: "Testing",
        creationDate: "2026-01-06",
        dueDate: "2026-01-11",
        status: "active",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 402,
        taskTitle: "Regression Testing",
        taskDescription: "Run regression test suite",
        taskPriority: "Low",
        category: "Testing",
        creationDate: "2026-01-03",
        dueDate: "2026-01-06",
        status: "completed",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 403,
        taskTitle: "Bug Reporting",
        taskDescription: "Document and report found issues",
        taskPriority: "Low",
        category: "Documentation",
        creationDate: "2026-01-04",
        dueDate: "2026-01-07",
        status: "failed",
        removalRequested: false,
        removalRequestedAt: null,
      },
    ],
  },

  {
    id: 5,
    employeeName: "Karan Patel",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        id: 501,
        taskTitle: "Server Monitoring",
        taskDescription: "Monitor server health and logs",
        taskPriority: "High",
        category: "DevOps",
        creationDate: "2026-01-07",
        dueDate: "2026-01-13",
        status: "new",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 502,
        taskTitle: "Backup Setup",
        taskDescription: "Configure daily database backups",
        taskPriority: "High",
        category: "DevOps",
        creationDate: "2026-01-02",
        dueDate: "2026-01-05",
        status: "completed",
        removalRequested: false,
        removalRequestedAt: null,
      },
      {
        id: 503,
        taskTitle: "Deploy Patch",
        taskDescription: "Deploy security patch to production",
        taskPriority: "High",
        category: "Deployment",
        creationDate: "2026-01-01",
        dueDate: "2026-01-03",
        status: "failed",
        removalRequested: false,
        removalRequestedAt: null,
      },
    ],
  },
];

export const admin = [
  {
    id: 1,
    adminName: "Akash Kumar",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
